# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{paperclipdb}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Caruso"]
  s.date = %q{2010-09-07}
  s.description = %q{Database storage support for paperclip file attachment plugin}
  s.email = %q{caruso.martin@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "app/controllers/paperclipdb/attachments_controller.rb",
     "app/models/paperclipdb/attachment.rb",
     "config/routes.rb",
     "db/migrate/20100906021538_attachments.rb",
     "generators/paperclipdb/USAGE",
     "generators/paperclipdb/paperclipdb_generator.rb",
     "init.rb",
     "install.rb",
     "lib/paperclipdb.rb",
     "lib/paperclipdb/storage.rb",
     "lib/tasks/paperclipdb.rake",
     "test/paperclipdb_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/mcaruso85/paperclipdb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Database storage support for paperclip file attachment plugin.}
  s.test_files = [
    "test/paperclipdb_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

